part of 'regex_simplifier.dart';

String _applyAlgebraicIdentities(String regex) {
  if (regex.isEmpty) return regex;

  String result = regex;

  // Apply identities in order
  result = _applyEmptySetIdentities(result);
  result = _applyEpsilonIdentities(result);
  result = _applyIdempotenceIdentities(result);

  return result;
}

/// Applies empty set (∅) identities
///
/// Empty set identities from regular expression algebra:
/// - ∅* → ε (Kleene star of empty set is epsilon)
/// - r|∅ → r (union with empty set is the other expression)
/// - ∅|r → r (union is commutative)
/// - r∅ → ∅ (concatenation with empty set is empty)
/// - ∅r → ∅ (concatenation with empty set is empty)
///
/// These identities are fundamental to regex simplification and
/// help reduce complex expressions generated by state elimination algorithms.
String _applyEmptySetIdentities(String regex) {
  String result = regex;

  // ∅* → ε
  result = result.replaceAll('∅*', 'ε');

  // r|∅ → r and ∅|r → r (union with empty set)
  result = _removeEmptySetFromUnion(result);

  // r∅ → ∅ and ∅r → ∅ (concatenation with empty set)
  result = _simplifyEmptySetConcatenation(result);

  return result;
}

/// Removes empty set from union expressions
///
/// Handles two cases:
/// 1. ∅|r → r (empty set at start of union)
/// 2. r|∅ → r (empty set at end of union)
///
/// Must be careful to handle multiple unions correctly,
/// e.g., ∅|a|b should become a|b, not just a|b with ∅ removed.
///
/// Time complexity: O(n)
/// Space complexity: O(n)
String _removeEmptySetFromUnion(String regex) {
  final buffer = StringBuffer();
  int i = 0;

  while (i < regex.length) {
    if (i < regex.length - 1 && regex[i] == '∅' && regex[i + 1] == '|') {
      // ∅|r → r (skip the empty set and union operator)
      i += 2; // Skip ∅|
    } else if (i < regex.length - 1 && regex[i] == '|' && regex[i + 1] == '∅') {
      // r|∅ → r (skip the union operator and empty set)
      i += 2; // Skip |∅
    } else {
      buffer.write(regex[i]);
      i++;
    }
  }

  return buffer.toString();
}

/// Simplifies concatenation with empty set
///
/// According to regex algebra: r∅ = ∅r = ∅
/// Any expression concatenated with the empty set results in the empty set.
///
/// Algorithm:
/// 1. Split regex into union segments (top-level | operators)
/// 2. For each segment, check if it contains ∅ in concatenation context
/// 3. If so, replace entire segment with ∅
///
/// Example:
/// - a∅b → ∅ (entire concatenation becomes empty)
/// - a|∅b → a|∅ (only second union segment becomes empty)
///
/// Time complexity: O(n)
/// Space complexity: O(n) for segments list
String _simplifyEmptySetConcatenation(String regex) {
  // Any concatenation with ∅ results in ∅
  // We need to identify concatenation segments and check if any contain ∅
  var depth = 0;
  var segmentStart = 0;

  for (var i = 0; i <= regex.length; i++) {
    final atEnd = i == regex.length;
    final isTopLevelUnion = !atEnd && regex[i] == '|' && depth == 0;

    if (atEnd || isTopLevelUnion) {
      final segment = regex.substring(segmentStart, i);
      if (segment.contains('∅') && !_hasTopLevelUnion(segment)) {
        return regex.replaceRange(segmentStart, i, '∅');
      }
      segmentStart = i + 1;
      continue;
    }

    if (regex[i] == '(') {
      depth++;
    } else if (regex[i] == ')') {
      depth--;
    }
  }

  return regex;
}

bool _hasTopLevelUnion(String segment) {
  var depth = 0;
  for (var i = 0; i < segment.length; i++) {
    final char = segment[i];
    if (char == '(') {
      depth++;
    } else if (char == ')') {
      depth--;
    } else if (char == '|' && depth == 0) {
      return true;
    }
  }
  return false;
}

/// Splits regex into concatenation segments (separated by |)
///
/// Splits at top-level union operators (|) only, respecting parentheses depth.
/// This allows us to process each union alternative independently.
///
/// Algorithm:
/// - Track parenthesis depth
/// - Split at | only when depth is 0 (top level)
/// - Preserve all characters within parenthesized groups
///
/// Examples:
/// - 'a|b|c' → ['a', 'b', 'c']
/// - '(a|b)|c' → ['(a|b)', 'c']
/// - 'a(b|c)d' → ['a(b|c)d'] (no top-level |)
///
/// Time complexity: O(n)
/// Space complexity: O(n) for segments list
List<String> _splitIntoConcatenationSegments(String regex) {
  final segments = <String>[];
  final buffer = StringBuffer();
  int depth = 0;

  for (int i = 0; i < regex.length; i++) {
    if (regex[i] == '(') {
      depth++;
      buffer.write(regex[i]);
    } else if (regex[i] == ')') {
      depth--;
      buffer.write(regex[i]);
    } else if (regex[i] == '|' && depth == 0) {
      // Top-level union operator - split here
      segments.add(buffer.toString());
      buffer.clear();
    } else {
      buffer.write(regex[i]);
    }
  }

  // Add remaining content
  if (buffer.isNotEmpty) {
    segments.add(buffer.toString());
  }

  return segments;
}

/// Applies epsilon (ε) identities
///
/// Epsilon identities from regular expression algebra:
/// - ε* → ε (Kleene star of epsilon is epsilon)
/// - rε → r (concatenating epsilon has no effect)
/// - εr → r (concatenating epsilon has no effect)
///
/// Epsilon is the identity element for concatenation, similar to
/// 1 being the identity for multiplication (1×x = x×1 = x).
///
/// These simplifications are crucial for readable output from
/// FA-to-regex conversion algorithms, which often generate
/// epsilon transitions during state elimination.
String _applyEpsilonIdentities(String regex) {
  String result = regex;

  // ε* → ε
  result = result.replaceAll('ε*', 'ε');

  // Remove epsilon from concatenation
  result = _removeEpsilonFromConcatenation(result);

  return result;
}

/// Removes epsilon from concatenation (εr → r, rε → r)
///
/// Algorithm:
/// 1. Scan for epsilon characters
/// 2. Check context - is epsilon in a concatenation or standalone?
/// 3. If in concatenation, remove it; if standalone, keep it
/// 4. Repeat until no changes (fixed point)
///
/// Context determination:
/// - Epsilon is in concatenation if preceded/followed by non-operator characters
/// - Epsilon is standalone if in union context (r|ε) or alone
///
/// Examples:
/// - aεb → ab (epsilon in concatenation)
/// - εa → a (epsilon at start of concatenation)
/// - aε → a (epsilon at end of concatenation)
/// - ε|a → ε|a (epsilon in union context, keep it)
/// - ε → ε (standalone epsilon, keep it)
/// - (ε)* → ε* → ε (epsilon with operator, handled by other rules)
///
/// Time complexity: O(n²) worst case (multiple passes × string length)
/// Space complexity: O(n) for buffer
String _removeEpsilonFromConcatenation(String regex) {
  // Remove ε in concatenation, but not in union
  // We need to be careful not to remove ε when it's the only element

  bool changed;
  do {
    changed = false;
    final buffer = StringBuffer();
    int i = 0;

    while (i < regex.length) {
      if (regex[i] == 'ε') {
        // Check context - is this in a concatenation?
        final before = i > 0 ? regex[i - 1] : '';
        final after = i < regex.length - 1 ? regex[i + 1] : '';

        // Skip ε if it's in concatenation (not after | or ( or start, and not before | or ) or postfix operators)
        final inConcatenation =
            (before != '' && before != '|' && before != '(') ||
                (after != '' &&
                    after != '|' &&
                    after != ')' &&
                    after != '*' &&
                    after != '+' &&
                    after != '?');

        if (inConcatenation && regex != 'ε') {
          // Skip the epsilon (remove it from concatenation)
          changed = true;
          i++;
          continue;
        }
      }

      buffer.write(regex[i]);
      i++;
    }

    if (changed) {
      regex = buffer.toString();
    }
  } while (changed);

  return regex;
}

/// Applies idempotence identities
///
/// Idempotence identities from regular expression algebra:
/// - r** → r* (multiple Kleene stars reduce to one)
/// - r|r → r (union with itself is itself)
///
/// Idempotence means "same power" - applying an operation multiple
/// times has the same effect as applying it once. These identities
/// help eliminate redundancy in regex expressions.
///
/// Examples:
/// - a** → a* (double star becomes single star)
/// - (a|b)*** → (a|b)* (triple star becomes single star)
/// - a|a|b → a|b (duplicate union alternative removed)
/// - (ab)|(ab) → ab (duplicate complex alternatives removed)
String _applyIdempotenceIdentities(String regex) {
  String result = regex;

  // r** → r*, r*** → r*, etc.
  result = _reduceMultipleStars(result);

  // r|r → r (union idempotence)
  result = _applyUnionIdempotence(result);

  return result;
}

/// Reduces multiple consecutive Kleene stars to a single star
///
/// According to regex algebra: (r*)* = r*
/// More generally: r** = r***, etc. - all reduce to r*
///
/// Algorithm:
/// - Scan for star operators
/// - When found, skip all consecutive stars
/// - Write only one star to output
///
/// This handles cases like:
/// - a** → a*
/// - (a|b)*** → (a|b)*
/// - (a*)** → a* (after first pass gives a**, which becomes a*)
///
/// Time complexity: O(n)
/// Space complexity: O(n) for buffer
String _reduceMultipleStars(String regex) {
  // Match any character followed by multiple stars and reduce to single star
  final buffer = StringBuffer();
  int i = 0;

  while (i < regex.length) {
    buffer.write(regex[i]);

    if (regex[i] == '*') {
      // Skip any additional consecutive stars
      while (i + 1 < regex.length && regex[i + 1] == '*') {
        i++;
      }
    }

    i++;
  }

  return buffer.toString();
}

/// Applies union idempotence (r|r → r)
///
/// According to regex algebra: r|r = r
/// A union of identical expressions can be reduced to a single instance.
///
/// Algorithm:
/// 1. Split regex into top-level union segments
/// 2. Track which segments we've seen using a set
/// 3. Keep only first occurrence of each unique segment
/// 4. Rejoin with | operator
///
/// This preserves order and removes duplicates, similar to
/// Python's dict.fromkeys() or SQL's SELECT DISTINCT.
///
/// Examples:
/// - a|a → a (simple duplicate)
/// - a|b|a → a|b (removes second occurrence of 'a')
/// - (ab)|(cd)|(ab) → (ab)|(cd) (complex expressions)
/// - a|b|c → a|b|c (no duplicates, unchanged)
///
/// Time complexity: O(n×m) where m is average segment length (for hashing)
/// Space complexity: O(k) where k is number of unique segments
String _applyUnionIdempotence(String regex) {
  // Split by | at top level and check for duplicates
  final segments = _splitIntoConcatenationSegments(regex);

  if (segments.length <= 1) return regex;

  // Remove duplicates while preserving order
  // Using LinkedHashSet would be ideal, but we use manual tracking for clarity
  final seen = <String>{};
  final unique = <String>[];

  for (final segment in segments) {
    if (!seen.contains(segment)) {
      seen.add(segment);
      unique.add(segment);
    }
  }

  // Only rebuild if we actually removed duplicates
  if (unique.length < segments.length) {
    return unique.join('|');
  }

  return regex;
}
