name: core_regex
description: Core regular expression and context-free grammar models
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1
  petitparser: ^7.0.0
  core_fa:
    path: ../core_fa

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^6.0.0
