name: serializers
description: Serialization and file I/O for automaton formats
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  freezed: ^2.4.7
  json_annotation: ^4.8.1
  xml: ^6.5.0
  core_fa:
    path: ../core_fa
  core_pda:
    path: ../core_pda
  core_tm:
    path: ../core_tm
  core_regex:
    path: ../core_regex

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  very_good_analysis: ^6.0.0
