name: viz
description: Visualization and rendering for automata
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  core_fa:
    path: ../core_fa
  core_pda:
    path: ../core_pda
  core_tm:
    path: ../core_tm
  core_regex:
    path: ../core_regex

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
