name: Claude Code Action

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  claude-code-action:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@claude')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Claude Code Action Official
        uses: anthropics/claude-code-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}